/**
 * SSC GD Mock Test – Seed Script
 * Seeds Mock Test 1 (80 questions) + Mock Test 2 (80 questions)
 * Run: node seed.js
 */
const mongoose = require('mongoose');
require('dotenv').config();
const Question = require('./models/Question');

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/sscgd';

// ─── MOCK TEST 1 — 80 Questions (20 GK + 20 Math + 20 Reasoning + 20 English) ──
const mockTest1 = [
    // ── GK (20) ──
    { question: 'Which is the largest continent in the world?', options: ['Africa', 'Asia', 'North America', 'Antarctica'], answer: 'Asia', explanation: 'Asia is the largest continent in area and population.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'The currency of Japan is:', options: ['Yuan', 'Won', 'Yen', 'Ringgit'], answer: 'Yen', explanation: 'The Yen is the official currency of Japan.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Who was the first woman Prime Minister of India?', options: ['Pratibha Patil', 'Indira Gandhi', 'Sushma Swaraj', 'Sarojini Naidu'], answer: 'Indira Gandhi', explanation: 'Indira Gandhi served as the first female PM of India.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Which gas is most abundant in the Earth\'s atmosphere?', options: ['Oxygen', 'Hydrogen', 'Nitrogen', 'Carbon Dioxide'], answer: 'Nitrogen', explanation: 'Nitrogen makes up about 78% of the atmosphere.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'ISRO headquarters is located in:', options: ['Mumbai', 'Chennai', 'Bengaluru', 'New Delhi'], answer: 'Bengaluru', explanation: 'ISRO is headquartered in Bengaluru, Karnataka.', subject: 'GK', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Which planet is known as the "Morning Star"?', options: ['Mars', 'Venus', 'Mercury', 'Jupiter'], answer: 'Venus', explanation: 'Venus is visible in the morning sky and called the Morning Star.', subject: 'GK', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Who is the author of "Discovery of India"?', options: ['Mahatma Gandhi', 'Jawaharlal Nehru', 'Rabindranath Tagore', 'Sardar Patel'], answer: 'Jawaharlal Nehru', explanation: 'Nehru wrote The Discovery of India while imprisoned at Ahmednagar Fort.', subject: 'GK', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Which instrument is used to measure blood pressure?', options: ['Thermometer', 'Barometer', 'Sphygmomanometer', 'Stethoscope'], answer: 'Sphygmomanometer', explanation: 'A sphygmomanometer measures arterial blood pressure.', subject: 'GK', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'In which year did the First World War begin?', options: ['1912', '1914', '1918', '1939'], answer: '1914', explanation: 'World War I began on July 28, 1914.', subject: 'GK', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'The "Statue of Liberty" was a gift to USA from which country?', options: ['UK', 'France', 'Germany', 'Spain'], answer: 'France', explanation: 'France gifted the Statue of Liberty to the United States.', subject: 'GK', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Which vitamin is essential for blood clotting?', options: ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'], answer: 'Vitamin K', explanation: 'Vitamin K plays a vital role in blood coagulation (clotting).', subject: 'GK', difficulty: 'Hard', mockTestNumber: 1, isActive: true },
    { question: 'The Quit India Movement was started in which year?', options: ['1940', '1942', '1945', '1947'], answer: '1942', explanation: 'Mahatma Gandhi launched the Quit India Movement in August 1942.', subject: 'GK', difficulty: 'Hard', mockTestNumber: 1, isActive: true },
    { question: 'Which layer of atmosphere contains the Ozone layer?', options: ['Troposphere', 'Stratosphere', 'Mesosphere', 'Thermosphere'], answer: 'Stratosphere', explanation: 'The ozone layer is in the stratosphere and protects us from UV radiation.', subject: 'GK', difficulty: 'Hard', mockTestNumber: 1, isActive: true },
    { question: 'Which is the highest waterfall in the world?', options: ['Niagara Falls', 'Angel Falls', 'Victoria Falls', 'Iguazu Falls'], answer: 'Angel Falls', explanation: 'Angel Falls in Venezuela is the world\'s highest uninterrupted waterfall (979 m).', subject: 'GK', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Who invented the Light Bulb?', options: ['Nikola Tesla', 'Thomas Edison', 'Alexander Graham Bell', 'Albert Einstein'], answer: 'Thomas Edison', explanation: 'Thomas Edison invented the first commercially practical incandescent light bulb.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Which is the largest animal on Earth?', options: ['African Elephant', 'Blue Whale', 'Colossal Squid', 'Giraffe'], answer: 'Blue Whale', explanation: 'The Blue Whale is the largest animal ever known to have existed on Earth.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'The capital of Germany is:', options: ['Munich', 'Frankfurt', 'Berlin', 'Hamburg'], answer: 'Berlin', explanation: 'Berlin is the capital and largest city of Germany.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Who was the first human to travel into space?', options: ['Neil Armstrong', 'Yuri Gagarin', 'Buzz Aldrin', 'Rakesh Sharma'], answer: 'Yuri Gagarin', explanation: 'Yuri Gagarin became the first human in space in 1961.', subject: 'GK', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Which is the deepest lake in the world?', options: ['Lake Superior', 'Lake Victoria', 'Lake Baikal', 'Lake Tanganyika'], answer: 'Lake Baikal', explanation: 'Lake Baikal in Siberia, Russia, is the world\'s deepest lake.', subject: 'GK', difficulty: 'Hard', mockTestNumber: 1, isActive: true },
    { question: 'Who is known as the "Father of Medicine"?', options: ['Aristotle', 'Hippocrates', 'Socrates', 'Plato'], answer: 'Hippocrates', explanation: 'Hippocrates is considered the founding figure of medicine.', subject: 'GK', difficulty: 'Hard', mockTestNumber: 1, isActive: true },

    // ── Math (20) ──
    { question: 'The average of first five prime numbers is:', options: ['5.2', '5.4', '5.6', '5.8'], answer: '5.6', explanation: 'First 5 primes: 2,3,5,7,11. Sum=28. Average=28/5=5.6.', subject: 'Math', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'If 20% of a number is 80, what is 50% of that number?', options: ['160', '200', '240', '250'], answer: '200', explanation: 'If 0.2x=80, x=400. 50% of 400=200.', subject: 'Math', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'The simple interest on ₹5000 at 5% for 2 years is:', options: ['₹400', '₹500', '₹600', '₹750'], answer: '₹500', explanation: 'SI=(P×R×T)/100=(5000×5×2)/100=₹500.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'A car covers 120 km in 3 hours. Its speed in m/s is:', options: ['10 m/s', '11.11 m/s', '12.5 m/s', '15 m/s'], answer: '11.11 m/s', explanation: 'Speed=40 km/h. 40×5/18≈11.11 m/s.', subject: 'Math', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'The HCF of 24, 36 and 48 is:', options: ['6', '8', '12', '18'], answer: '12', explanation: '12 is the highest number dividing 24, 36, and 48 exactly.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'A person buys for ₹300 and sells for ₹360. Profit % is:', options: ['15%', '20%', '25%', '30%'], answer: '20%', explanation: 'Profit=₹60. Profit%=(60/300)×100=20%.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'The sum of first 50 natural numbers is:', options: ['1225', '1275', '1300', '2550'], answer: '1275', explanation: 'Sum=n(n+1)/2=50×51/2=1275.', subject: 'Math', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'What is 5! (5 factorial)?', options: ['60', '100', '120', '150'], answer: '120', explanation: '5!=5×4×3×2×1=120.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'A circle has radius 7 cm. Its circumference is (π=22/7):', options: ['22 cm', '44 cm', '88 cm', '154 cm'], answer: '44 cm', explanation: 'Circumference=2πr=2×(22/7)×7=44 cm.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Solve for x: 3(x − 4) = 15', options: ['7', '8', '9', '10'], answer: '9', explanation: '3x−12=15 → 3x=27 → x=9.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'The area of a rectangle with length 10m and width 5m is:', options: ['15 m²', '30 m²', '50 m²', '60 m²'], answer: '50 m²', explanation: 'Area=length×width=10×5=50 m².', subject: 'Math', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'The volume of a cuboid with dimensions 3, 4 and 5 cm is:', options: ['12 cm³', '20 cm³', '60 cm³', '70 cm³'], answer: '60 cm³', explanation: 'Volume=3×4×5=60 cm³.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Which of the following is a prime number?', options: ['91', '93', '97', '99'], answer: '97', explanation: '97 has no factors other than 1 and itself.', subject: 'Math', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'What is 25% of 500?', options: ['100', '125', '150', '200'], answer: '125', explanation: '25% of 500=(25/100)×500=125.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Convert 54 km/h into m/s:', options: ['10 m/s', '15 m/s', '18 m/s', '20 m/s'], answer: '15 m/s', explanation: '54×(5/18)=15 m/s.', subject: 'Math', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'The ratio of boys to girls is 4:5. If boys=20, girls are:', options: ['20', '25', '30', '35'], answer: '25', explanation: '4 units=20, 1 unit=5. Girls=5×5=25.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Solve: 2x + 7 = 15', options: ['2', '4', '6', '8'], answer: '4', explanation: '2x=8 → x=4.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'The mean of first ten natural numbers is:', options: ['5', '5.5', '6', '6.5'], answer: '5.5', explanation: 'Sum=55. Mean=55/10=5.5.', subject: 'Math', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'A triangle has angles in ratio 1:2:3. The smallest angle is:', options: ['20°', '30°', '45°', '60°'], answer: '30°', explanation: '1x+2x+3x=180 → x=30°.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Volume of a cube with side 4 cm is:', options: ['16 cm³', '32 cm³', '64 cm³', '96 cm³'], answer: '64 cm³', explanation: 'Volume=4³=64 cm³.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 1, isActive: true },

    // ── Reasoning (20) ──
    { question: 'Complete the pattern: 1, 4, 9, 16, ?', options: ['20', '24', '25', '30'], answer: '25', explanation: 'Series of squares: 1²,2²,3²,4². Next is 5²=25.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'If "Red" is called "Blue", "Blue" is called "Green", what is the color of the sky?', options: ['Blue', 'Green', 'Yellow', 'Red'], answer: 'Green', explanation: 'Sky is Blue. In this code, Blue is called Green.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Complete the series: 100, 90, 81, 73, ?', options: ['65', '66', '67', '68'], answer: '66', explanation: 'Differences: -10,-9,-8,-7. 73-7=66.', subject: 'Reasoning', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'ODD one out: Lion, Tiger, Leopard, Elephant', options: ['Lion', 'Tiger', 'Leopard', 'Elephant'], answer: 'Elephant', explanation: 'Elephant is a herbivore; others are carnivores from the cat family.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Sun : Heat :: Moon : ?', options: ['Star', 'Light', 'Reflection', 'Darkness'], answer: 'Light', explanation: 'Sun provides heat; Moon provides light.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'If MONDAY is the 1st day of the month, which day is the 15th?', options: ['Monday', 'Tuesday', 'Sunday', 'Saturday'], answer: 'Monday', explanation: 'Days repeat every 7 days. 1st, 8th, 15th are all the same day.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Neha said: "His brother is the only son of my father." How is Neha related to him?', options: ['Mother', 'Sister', 'Daughter', 'Aunt'], answer: 'Sister', explanation: 'Only son of Neha\'s father is Neha\'s brother → they are siblings.', subject: 'Reasoning', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Book : Page :: Flower : ?', options: ['Petal', 'Fruit', 'Seed', 'Leaf'], answer: 'Petal', explanation: 'A book is made of pages; a flower is made of petals.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Find the next term: B2, D4, F6, ?', options: ['G7', 'H8', 'I9', 'J10'], answer: 'H8', explanation: 'Letters skip one: B,D,F,H. Numbers: 2,4,6,8.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'If 5 + 3 = 28, 9 + 1 = 810, then 7 + 4 = ?', options: ['311', '113', '283', '312'], answer: '311', explanation: '(7-4)=3 and (7+4)=11 → 311.', subject: 'Reasoning', difficulty: 'Hard', mockTestNumber: 1, isActive: true },
    { question: 'A clock shows 3:00. Angle between hands is:', options: ['60°', '90°', '120°', '180°'], answer: '90°', explanation: 'Each hour gap is 30°. 3×30°=90°.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Point: Ravi says "He is the son of my father\'s only brother." How is the man related to Ravi?', options: ['Brother', 'Nephew', 'Cousin', 'Uncle'], answer: 'Cousin', explanation: 'Son of father\'s brother is a cousin.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Find next in series: 1, 8, 27, 64, ?', options: ['100', '121', '125', '144'], answer: '125', explanation: 'Cubes: 1³,2³,3³,4³. Next is 5³=125.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Statement: All books are pens. All pens are pencils. Conclusion: All books are pencils.', options: ['Follows', 'Does not follow', 'Partially follows', 'None'], answer: 'Follows', explanation: 'If all A are B and all B are C, then all A are C.', subject: 'Reasoning', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'ODD one out: Red, Blue, Yellow, Pencil', options: ['Red', 'Blue', 'Yellow', 'Pencil'], answer: 'Pencil', explanation: 'Red, Blue, Yellow are colors; Pencil is a writing instrument.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Dog : Bark :: Cat : ?', options: ['Roar', 'Moo', 'Meow', 'Bleat'], answer: 'Meow', explanation: 'Bark is the sound of a dog; Meow is the sound of a cat.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'If day after tomorrow is Sunday, what day was yesterday?', options: ['Wednesday', 'Thursday', 'Friday', 'Saturday'], answer: 'Thursday', explanation: 'Day after tomorrow=Sunday → Tomorrow=Saturday → Today=Friday → Yesterday=Thursday.', subject: 'Reasoning', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'In a class of 40, Rahul is 15th from top. Rank from bottom is:', options: ['25', '26', '27', '28'], answer: '26', explanation: 'Rank from bottom=(40-15)+1=26.', subject: 'Reasoning', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Find missing: 4, 9, 20, 43, ?', options: ['86', '90', '92', '95'], answer: '90', explanation: 'Pattern: n×2+1: 4×2+1=9, 9×2+2=20, 20×2+3=43, 43×2+4=90.', subject: 'Reasoning', difficulty: 'Hard', mockTestNumber: 1, isActive: true },
    { question: 'ACEG : BDFH :: PRTV : ?', options: ['QSUX', 'QSUW', 'QSTW', 'RSUV'], answer: 'QSUW', explanation: 'Each letter is shifted by +1: P+1=Q, R+1=S, T+1=U, V+1=W.', subject: 'Reasoning', difficulty: 'Medium', mockTestNumber: 1, isActive: true },

    // ── English (20) ──
    { question: 'Fill in: Neither of the two boys _____ present.', options: ['are', 'were', 'was', 'have been'], answer: 'was', explanation: '"Neither of" takes a singular verb.', subject: 'English', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Synonym of "ABANDON":', options: ['Keep', 'Forsake', 'Support', 'Cherish'], answer: 'Forsake', explanation: 'Abandon and Forsake both mean to leave or desert.', subject: 'English', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Antonym of "FRAGILE":', options: ['Weak', 'Robust', 'Brittle', 'Delicate'], answer: 'Robust', explanation: 'Fragile means easily broken; Robust means strong.', subject: 'English', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Change to Indirect: He said, "I am busy."', options: ['He said that he was busy.', 'He says that he is busy.', 'He said he is busy.', 'He told he was busy.'], answer: 'He said that he was busy.', explanation: 'Present simple → past simple in indirect speech.', subject: 'English', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Meaning of "Piece of cake":', options: ['Delicious food', 'Something very easy', 'A small portion', 'To celebrate'], answer: 'Something very easy', explanation: '"Piece of cake" means a very easy task.', subject: 'English', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'One word substitution: A person who loves books.', options: ['Bibliophile', 'Philanthropist', 'Polyglot', 'Misanthrope'], answer: 'Bibliophile', explanation: 'A bibliophile is a person who loves collecting books.', subject: 'English', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Fill in: I am looking forward to _____ you.', options: ['meet', 'meeting', 'met', 'be meeting'], answer: 'meeting', explanation: '"Look forward to" is followed by the gerund (-ing) form.', subject: 'English', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Find the error: "The sceneries of Kashmir are beautiful."', options: ['The sceneries', 'of Kashmir', 'are beautiful', 'No error'], answer: 'The sceneries', explanation: '"Scenery" is uncountable and has no plural form.', subject: 'English', difficulty: 'Hard', mockTestNumber: 1, isActive: true },
    { question: 'Collective noun for birds:', options: ['Flock', 'Herd', 'Pack', 'School'], answer: 'Flock', explanation: 'A group of birds is called a flock.', subject: 'English', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Identify the Tense: "I have been writing for two hours."', options: ['Present Perfect', 'Present Perfect Continuous', 'Past Perfect Continuous', 'Future Perfect'], answer: 'Present Perfect Continuous', explanation: '"Have been + verb-ing" is Present Perfect Continuous.', subject: 'English', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Antonym of "OPTIMIST":', options: ['Positivist', 'Pessimist', 'Realist', 'Idealist'], answer: 'Pessimist', explanation: 'Optimist looks at the bright side; Pessimist at the dark side.', subject: 'English', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Meaning of "Break the ice":', options: ['To start a fire', 'To start a conversation', 'To end a relationship', 'To cause trouble'], answer: 'To start a conversation', explanation: 'Break the ice means to relieve tension or start a conversation.', subject: 'English', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Fill in: If I _____ you, I would not do that.', options: ['am', 'was', 'were', 'had been'], answer: 'were', explanation: 'In subjunctive mood, "were" is used for all persons.', subject: 'English', difficulty: 'Hard', mockTestNumber: 1, isActive: true },
    { question: 'Correct spelling:', options: ['Recieve', 'Receive', 'Receeve', 'Receieve'], answer: 'Receive', explanation: '"i before e except after c" — so Receive is correct.', subject: 'English', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Which is in Future Continuous tense?', options: ['I will go', 'I will have gone', 'I will be going', 'I would go'], answer: 'I will be going', explanation: 'Future Continuous = "will be" + verb-ing.', subject: 'English', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'Fill in: The book is _____ the table.', options: ['in', 'at', 'on', 'with'], answer: 'on', explanation: '"on" denotes surface contact.', subject: 'English', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Which article before "Eiffel Tower"?', options: ['A', 'An', 'The', 'No article'], answer: 'The', explanation: 'Definite article "The" is used before unique monuments.', subject: 'English', difficulty: 'Easy', mockTestNumber: 1, isActive: true },
    { question: 'Find the error: "Each of the students have finished the test."', options: ['Each of', 'the students', 'have finished', 'No error'], answer: 'have finished', explanation: '"Each" is singular; should be "has finished".', subject: 'English', difficulty: 'Hard', mockTestNumber: 1, isActive: true },
    { question: 'Change to Passive: "She sings a song."', options: ['A song is sung by her.', 'A song was sung by her.', 'A song has been sung by her.', 'A song is being sung by her.'], answer: 'A song is sung by her.', explanation: 'Object becomes subject; "is sung" is present passive.', subject: 'English', difficulty: 'Medium', mockTestNumber: 1, isActive: true },
    { question: 'What is the meaning of "AMNESTY"?', options: ['Enemy', 'Official pardon', 'Anger', 'Friendship'], answer: 'Official pardon', explanation: 'Amnesty is an official pardon for political offenses.', subject: 'English', difficulty: 'Hard', mockTestNumber: 1, isActive: true },
];

// ─── MOCK TEST 2 — 80 Questions (20 GK + 20 Math + 20 Reasoning + 20 English) ──
const mockTest2 = [
    // ── GK (20) ──
    { question: 'Who built the Taj Mahal?', options: ['Akbar', 'Humayun', 'Shah Jahan', 'Aurangzeb'], answer: 'Shah Jahan', explanation: 'Shah Jahan built the Taj Mahal in memory of his wife Mumtaz Mahal.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'What is the national bird of India?', options: ['Parrot', 'Eagle', 'Peacock', 'Swan'], answer: 'Peacock', explanation: 'The Indian Peacock is the national bird of India.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'The capital of Canada is:', options: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'], answer: 'Ottawa', explanation: 'Ottawa is the capital city of Canada.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Who is known as the Iron Man of India?', options: ['Mahatma Gandhi', 'Jawaharlal Nehru', 'Sardar Vallabhbhai Patel', 'Subhas Chandra Bose'], answer: 'Sardar Vallabhbhai Patel', explanation: 'Sardar Patel is called the Iron Man for unifying Indian states.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'The Constitution of India was adopted on:', options: ['15 August 1947', '26 January 1950', '26 November 1949', '2 October 1948'], answer: '26 November 1949', explanation: 'The Constitution was adopted on 26 November 1949 and came into effect on 26 January 1950.', subject: 'GK', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Which river is called the "National River" of India?', options: ['Yamuna', 'Ganga', 'Brahmaputra', 'Godavari'], answer: 'Ganga', explanation: 'The Ganga (Ganges) is the national river of India.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Who was the first Indian to go to space?', options: ['Kalpana Chawla', 'Sunita Williams', 'Rakesh Sharma', 'A.P.J. Abdul Kalam'], answer: 'Rakesh Sharma', explanation: 'Rakesh Sharma traveled to space in 1984 aboard Soyuz T-11.', subject: 'GK', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'What is the national tree of India?', options: ['Neem', 'Peepal', 'Banyan', 'Mango'], answer: 'Banyan', explanation: 'The Banyan tree (Ficus benghalensis) is the national tree of India.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Which state has the longest coastline in India?', options: ['Maharashtra', 'Andhra Pradesh', 'Gujarat', 'Tamil Nadu'], answer: 'Gujarat', explanation: 'Gujarat has the longest coastline of any Indian state (~1,600 km).', subject: 'GK', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'What is the pH value of pure water?', options: ['5', '6', '7', '8'], answer: '7', explanation: 'Pure water is neutral with a pH of exactly 7.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Who discovered the electron?', options: ['Ernest Rutherford', 'J.J. Thomson', 'Niels Bohr', 'Albert Einstein'], answer: 'J.J. Thomson', explanation: 'J.J. Thomson discovered the electron in 1897.', subject: 'GK', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'What is the hardest natural substance?', options: ['Gold', 'Iron', 'Diamond', 'Quartz'], answer: 'Diamond', explanation: 'Diamond is the hardest naturally occurring substance (10 on Mohs scale).', subject: 'GK', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Who painted the "Mona Lisa"?', options: ['Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Picasso'], answer: 'Leonardo da Vinci', explanation: 'Leonardo da Vinci painted the Mona Lisa in the early 16th century.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Which is the longest bone in the human body?', options: ['Spine', 'Tibia', 'Femur', 'Humerus'], answer: 'Femur', explanation: 'The femur (thigh bone) is the longest bone in the human body.', subject: 'GK', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'The national anthem of India was written by:', options: ['Bankim Chandra Chattopadhyay', 'Rabindranath Tagore', 'Sarojini Naidu', 'Subramanya Bharati'], answer: 'Rabindranath Tagore', explanation: 'Jana Gana Mana was written by Rabindranath Tagore.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: '"Wings of Fire" is an autobiography of:', options: ['Amitabh Bachchan', 'Sachin Tendulkar', 'A.P.J. Abdul Kalam', 'Narendra Modi'], answer: 'A.P.J. Abdul Kalam', explanation: 'Wings of Fire is the autobiography of Dr. A.P.J. Abdul Kalam.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Which vitamin is produced by the human body when exposed to sunlight?', options: ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'], answer: 'Vitamin D', explanation: 'Vitamin D is synthesized in the skin when exposed to UVB radiation from sunlight.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'The "Doctrine of Lapse" was introduced by:', options: ['Lord Wellesley', 'Lord Cornwallis', 'Lord Dalhousie', 'Lord Curzon'], answer: 'Lord Dalhousie', explanation: 'Lord Dalhousie introduced the Doctrine of Lapse to annex Indian states.', subject: 'GK', difficulty: 'Hard', mockTestNumber: 2, isActive: true },
    { question: 'The full form of CPU is:', options: ['Central Power Unit', 'Central Processing Unit', 'Computer Processing Unit', 'Central Program Unit'], answer: 'Central Processing Unit', explanation: 'CPU stands for Central Processing Unit, the brain of the computer.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Which is the smallest continent by land area?', options: ['Europe', 'Australia', 'Antarctica', 'South America'], answer: 'Australia', explanation: 'Australia is the smallest of the seven continents.', subject: 'GK', difficulty: 'Easy', mockTestNumber: 2, isActive: true },

    // ── Math (20) ──
    { question: 'A train travels 600 km in 5 hours. Its speed is:', options: ['100 km/h', '110 km/h', '120 km/h', '130 km/h'], answer: '120 km/h', explanation: 'Speed=Distance/Time=600/5=120 km/h.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Compound interest on ₹10000 at 10% for 2 years is:', options: ['₹1000', '₹2000', '₹2100', '₹2200'], answer: '₹2100', explanation: 'CI=P[(1+r/100)^t - 1]=10000[(1.1)²-1]=10000×0.21=₹2100.', subject: 'Math', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'A shopkeeper gives 20% discount on ₹500. Selling price is:', options: ['₹350', '₹380', '₹400', '₹420'], answer: '₹400', explanation: 'Discount=20% of 500=₹100. SP=500-100=₹400.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Perimeter of a square with side 7 cm is:', options: ['14 cm', '21 cm', '28 cm', '49 cm'], answer: '28 cm', explanation: 'Perimeter=4×side=4×7=28 cm.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'What is 15% of 80?', options: ['10', '12', '14', '15'], answer: '12', explanation: '15% of 80=(15/100)×80=12.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'LCM of 12 and 18 is:', options: ['6', '24', '36', '72'], answer: '36', explanation: 'LCM(12,18)=36.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'A pipe fills a tank in 6 hours. Part filled in 2 hours is:', options: ['1/6', '1/4', '1/3', '1/2'], answer: '1/3', explanation: 'In 1 hr it fills 1/6. In 2 hrs = 2/6 = 1/3.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'The median of 3, 5, 7, 9, 11 is:', options: ['5', '6', '7', '9'], answer: '7', explanation: 'Middle value of ordered set 3,5,7,9,11 is 7.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Sum of all interior angles of a hexagon is:', options: ['540°', '620°', '720°', '900°'], answer: '720°', explanation: 'Sum=(n-2)×180=(6-2)×180=4×180=720°.', subject: 'Math', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'A and B together finish a job in 12 days. A alone takes 20 days. B alone takes:', options: ['24 days', '28 days', '30 days', '32 days'], answer: '30 days', explanation: '1/B=1/12-1/20=5/60-3/60=2/60=1/30. B=30 days.', subject: 'Math', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'The square root of 1764 is:', options: ['40', '42', '44', '46'], answer: '42', explanation: '42×42=1764.', subject: 'Math', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Boat speed in still water: 8 km/h, stream speed: 2 km/h. Speed downstream:', options: ['6 km/h', '8 km/h', '10 km/h', '12 km/h'], answer: '10 km/h', explanation: 'Downstream speed=boat+stream=8+2=10 km/h.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: '5 men can do work in 8 days. 4 men can do it in:', options: ['8 days', '9 days', '10 days', '12 days'], answer: '10 days', explanation: '5×8=4×D. D=40/4=10 days.', subject: 'Math', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Area of a triangle with base 10 cm and height 8 cm:', options: ['20 cm²', '40 cm²', '60 cm²', '80 cm²'], answer: '40 cm²', explanation: 'Area=½×base×height=½×10×8=40 cm².', subject: 'Math', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: '121 × 121 = ?', options: ['13321', '14421', '14641', '15641'], answer: '14641', explanation: '121²=14641.', subject: 'Math', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'The mode of 2, 3, 3, 4, 5, 5, 5 is:', options: ['2', '3', '4', '5'], answer: '5', explanation: '5 appears most frequently (3 times) so mode=5.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'What is 30% of 200?', options: ['40', '50', '60', '70'], answer: '60', explanation: '30% of 200=(30/100)×200=60.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Find the value of x: x/5 = 9', options: ['35', '40', '45', '50'], answer: '45', explanation: 'x=9×5=45.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Simplify: 3/4 + 5/8', options: ['8/12', '11/8', '9/8', '7/8'], answer: '11/8', explanation: '3/4+5/8=6/8+5/8=11/8.', subject: 'Math', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'If x:y=3:4 and y:z=8:9, then x:z is:', options: ['1:2', '2:3', '3:4', '4:5'], answer: '2:3', explanation: 'x:y=3:4, y:z=8:9 → x:z=(3×8):(4×9)=24:36=2:3.', subject: 'Math', difficulty: 'Hard', mockTestNumber: 2, isActive: true },

    // ── Reasoning (20) ──
    { question: 'Carpenter : Wood :: Painter : ?', options: ['Brush', 'Canvas', 'Color', 'Easel'], answer: 'Canvas', explanation: 'Carpenter works with Wood; Painter works with Canvas.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Find next: 3, 6, 11, 18, 27, ?', options: ['34', '36', '38', '40'], answer: '38', explanation: 'Differences: 3,5,7,9,11. Next=27+11=38.', subject: 'Reasoning', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'John is taller than Peter. Peter is taller than Sam. Who is shortest?', options: ['John', 'Peter', 'Sam', 'Cannot determine'], answer: 'Sam', explanation: 'John > Peter > Sam. So Sam is shortest.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'In a row, Ram is 7th from left and 13th from right. Total students:', options: ['18', '19', '20', '21'], answer: '19', explanation: 'Total=7+13-1=19.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'ODD one out: Cow, Goat, Hen, Dog', options: ['Cow', 'Goat', 'Hen', 'Dog'], answer: 'Dog', explanation: 'Cow, Goat, Hen are farm animals raised for food/milk/eggs; Dog is a pet.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Fire : Ash :: Water : ?', options: ['Ice', 'Rain', 'Steam', 'River'], answer: 'Steam', explanation: 'Fire produces Ash; Water (when heated) produces Steam.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'A is east of B. C is north of B. In which direction is A from C?', options: ['North-East', 'South', 'South-East', 'East'], answer: 'South-East', explanation: 'B is center, A is East, C is North. So A is South-East of C.', subject: 'Reasoning', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Complete: 2, 5, 10, 17, 26, ?', options: ['35', '37', '39', '41'], answer: '37', explanation: 'Differences: 3,5,7,9,11. Next=26+11=37.', subject: 'Reasoning', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Arrange in logical order: 1.Foundation 2.Roof 3.Walls 4.Floor', options: ['1,2,3,4', '1,4,3,2', '2,3,4,1', '4,1,3,2'], answer: '1,4,3,2', explanation: 'Building is constructed: Foundation → Floor → Walls → Roof.', subject: 'Reasoning', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Statement: No dogs are cats. Conclusion: Some cats are not dogs.', options: ['Follows', 'Does not follow', 'Cannot be determined', 'Partially follows'], answer: 'Follows', explanation: 'If no dogs are cats, then some (or all) cats are not dogs.', subject: 'Reasoning', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Square : 4 :: Hexagon : ?', options: ['5', '6', '7', '8'], answer: '6', explanation: 'Square has 4 sides; Hexagon has 6 sides.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'ODD one out: BDFH, PRTV, ACEG, LMNO', options: ['BDFH', 'PRTV', 'ACEG', 'LMNO'], answer: 'LMNO', explanation: 'BDFH, PRTV, ACEG all skip one letter; LMNO has consecutive letters.', subject: 'Reasoning', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: '6 : 36 :: 8 : ?', options: ['48', '56', '64', '72'], answer: '64', explanation: '6²=36, so 8²=64.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'A walks 5km North, 3km East, then 5km South. How far from start?', options: ['1 km', '2 km', '3 km', '5 km'], answer: '3 km', explanation: '5km North and 5km South cancel. Remaining: 3km East from start.', subject: 'Reasoning', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'If CAT = 3-1-20, what is BAT?', options: ['2-1-19', '2-1-20', '3-2-20', '1-2-20'], answer: '2-1-20', explanation: 'B=2, A=1, T=20. BAT=2-1-20.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'A man faces North, turns 90° clockwise, then 90° anticlockwise. He now faces:', options: ['North', 'South', 'East', 'West'], answer: 'North', explanation: '+90° clockwise → East. Then -90° (anticlockwise) → back to North.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Find next letter: D, G, J, M, ?', options: ['N', 'O', 'P', 'Q'], answer: 'P', explanation: 'Each letter is 3 positions ahead: D+3=G, G+3=J, J+3=M, M+3=P.', subject: 'Reasoning', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'If SUNDAY = XZSIEB, how is MONDAY coded?', options: ['RNFCBX', 'RNCIEB', 'RNFIBX', 'RNDIBX'], answer: 'RNFCBX', explanation: 'Each letter shifted by +5: M+5=R, O+5=T... (shift pattern applies).', subject: 'Reasoning', difficulty: 'Hard', mockTestNumber: 2, isActive: true },
    { question: 'How many triangles are in a triangle divided by 2 lines from each vertex?', options: ['4', '6', '8', '10'], answer: '6', explanation: 'A triangle divided by medians contains 6 smaller triangles.', subject: 'Reasoning', difficulty: 'Hard', mockTestNumber: 2, isActive: true },
    { question: 'Pointing to a photo, a man says "Her mother is the wife of my father\'s son." Who is in photo?', options: ['His daughter', 'His niece', 'His sister', 'His wife'], answer: 'His daughter', explanation: 'Father\'s son = himself. Wife of himself = his wife. Her mother = his wife → the girl is his daughter.', subject: 'Reasoning', difficulty: 'Hard', mockTestNumber: 2, isActive: true },

    // ── English (20) ──
    { question: 'Synonym of "COURAGEOUS":', options: ['Timid', 'Brave', 'Weak', 'Cowardly'], answer: 'Brave', explanation: 'Courageous and Brave both mean having bravery.', subject: 'English', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Antonym of "GENUINE":', options: ['Real', 'Authentic', 'Fake', 'True'], answer: 'Fake', explanation: 'Genuine means real/authentic; Fake is its antonym.', subject: 'English', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Fill in: She _____ to school every day.', options: ['go', 'goes', 'gone', 'going'], answer: 'goes', explanation: 'Third person singular (she) takes "goes" in simple present.', subject: 'English', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Passive voice: "They built the bridge."', options: ['The bridge was built by them.', 'The bridge is built by them.', 'The bridge had been built by them.', 'The bridge will be built by them.'], answer: 'The bridge was built by them.', explanation: 'Past simple active → was/were + past participle.', subject: 'English', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Meaning of "Hit the nail on the head":', options: ['To cause injury', 'To say exactly the right thing', 'To fail completely', 'To do a repair job'], answer: 'To say exactly the right thing', explanation: '"Hit the nail on the head" means to be exactly right.', subject: 'English', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Find the error: "She don\'t know the answer."', options: ['She', 'don\'t', 'know', 'the answer'], answer: 'don\'t', explanation: '"She" (third person singular) requires "doesn\'t", not "don\'t".', subject: 'English', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'One word for "Fear of heights":', options: ['Claustrophobia', 'Acrophobia', 'Agoraphobia', 'Hydrophobia'], answer: 'Acrophobia', explanation: 'Acrophobia is the extreme fear of heights.', subject: 'English', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Fill in: He is senior _____ me.', options: ['than', 'from', 'to', 'over'], answer: 'to', explanation: '"Senior to" is the correct preposition usage.', subject: 'English', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Identify the tense: "I had been waiting for an hour."', options: ['Past Perfect', 'Past Perfect Continuous', 'Past Continuous', 'Present Perfect'], answer: 'Past Perfect Continuous', explanation: '"Had been + verb-ing" is Past Perfect Continuous.', subject: 'English', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Synonym of "MELANCHOLY":', options: ['Joy', 'Anger', 'Sadness', 'Fear'], answer: 'Sadness', explanation: 'Melancholy means deep sadness or gloom.', subject: 'English', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Antonym of "TRANSPARENT":', options: ['Clear', 'Visible', 'Opaque', 'Shiny'], answer: 'Opaque', explanation: 'Transparent allows light through; Opaque does not.', subject: 'English', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Fill in: _____ apple a day keeps the doctor away.', options: ['A', 'An', 'The', 'No article'], answer: 'An', explanation: '"An" is used before words starting with a vowel sound.', subject: 'English', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Meaning of "Bite the bullet":', options: ['To eat quickly', 'To endure a painful situation', 'To speak frankly', 'To work hard'], answer: 'To endure a painful situation', explanation: '"Bite the bullet" means to endure a painful or difficult situation.', subject: 'English', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'One word substitution: A speech given to oneself:', options: ['Monologue', 'Soliloquy', 'Dialogue', 'Oration'], answer: 'Soliloquy', explanation: 'A soliloquy is a speech in which one speaks their thoughts aloud alone.', subject: 'English', difficulty: 'Hard', mockTestNumber: 2, isActive: true },
    { question: 'Find the error: "He doesn\'t knows me."', options: ['He', 'doesn\'t', 'knows', 'me'], answer: 'knows', explanation: 'After "doesn\'t", the base form is used: "doesn\'t know".', subject: 'English', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Fill in: Neither he nor his friends _____ present.', options: ['is', 'was', 'were', 'are'], answer: 'were', explanation: 'With "neither...nor", verb agrees with the nearest subject (friends = plural → were).', subject: 'English', difficulty: 'Hard', mockTestNumber: 2, isActive: true },
    { question: 'Direct speech: She said that she was tired.', options: ['"I am tired," she said.', '"She is tired," she said.', '"I was tired," she said.', '"I will be tired," she said.'], answer: '"I am tired," she said.', explanation: 'In direct speech, past tense in indirect becomes present tense.', subject: 'English', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
    { question: 'Synonym of "ENORMOUS":', options: ['Tiny', 'Huge', 'Average', 'Slim'], answer: 'Huge', explanation: 'Enormous and Huge both mean very large.', subject: 'English', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Antonym of "VICTORY":', options: ['Success', 'Win', 'Defeat', 'Achievement'], answer: 'Defeat', explanation: 'Victory means winning; Defeat means losing.', subject: 'English', difficulty: 'Easy', mockTestNumber: 2, isActive: true },
    { question: 'Correctly spelt word:', options: ['Accomodation', 'Accommodation', 'Acomodation', 'Acommodation'], answer: 'Accommodation', explanation: 'Accommodation has double "c" and double "m".', subject: 'English', difficulty: 'Medium', mockTestNumber: 2, isActive: true },
];

async function seedQuestions() {
    try {
        await mongoose.connect(MONGODB_URI);
        console.log('✅ Connected to MongoDB');

        await Question.deleteMany({});
        console.log('🗑️  Cleared existing questions');

        const allQuestions = [...mockTest1, ...mockTest2];
        const inserted = await Question.insertMany(allQuestions);
        console.log(`✅ Seeded ${inserted.length} questions successfully!`);
        console.log(`   Mock Test 1: ${mockTest1.length} questions`);
        console.log(`   Mock Test 2: ${mockTest2.length} questions`);

        process.exit(0);
    } catch (error) {
        console.error('❌ Seed error:', error);
        process.exit(1);
    }
}

seedQuestions();
