/**
 * SSC GD Mock Test – Question Seed Script
 * Run: node seed.js
 * Seeds 40+ questions across GK, Math, Reasoning, and English subjects.
 */

const mongoose = require('mongoose');
require('dotenv').config();
const Question = require('./models/Question');

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/sscgd';

const questions = [
    {
        question: 'Which is the largest continent in the world?',
        options: ['Africa', 'Asia', 'North America', 'Antarctica'],
        answer: 'Asia',
        explanation: 'Asia is the largest continent both in terms of area and population.',
        subject: 'GK',
        difficulty: 'Easy',
    },
    {
        question: 'The currency of Japan is:',
        options: ['Yuan', 'Won', 'Yen', 'Ringgit'],
        answer: 'Yen',
        explanation: 'The Yen is the official currency of Japan.',
        subject: 'GK',
        difficulty: 'Easy',
    },
    {
        question: 'Who was the first woman Prime Minister of India?',
        options: ['Pratibha Patil', 'Indira Gandhi', 'Sushma Swaraj', 'Sarojini Naidu'],
        answer: 'Indira Gandhi',
        explanation: 'Indira Gandhi served as the first and only female Prime Minister of India.',
        subject: 'GK',
        difficulty: 'Easy',
    },
    {
        question: 'Which is the smallest continent by land area?',
        options: ['Europe', 'Australia', 'Antarctica', 'South America'],
        answer: 'Australia',
        explanation: 'Australia is often referred to as an "island continent" and is the smallest of the seven.',
        subject: 'GK',
        difficulty: 'Easy',
    },
    {
        question: 'Which gas is most abundant in the Earth\'s atmosphere?',
        options: ['Oxygen', 'Hydrogen', 'Nitrogen', 'Carbon Dioxide'],
        answer: 'Nitrogen',
        explanation: 'Nitrogen makes up about 78% of the Earth\'s atmosphere.',
        subject: 'GK',
        difficulty: 'Easy',
    },
    {
        question: 'The headquarters of ISRO is located in:',
        options: ['Mumbai', 'Chennai', 'Bengaluru', 'New Delhi'],
        answer: 'Bengaluru',
        explanation: 'The Indian Space Research Organisation (ISRO) is headquartered in Bengaluru.',
        subject: 'GK',
        difficulty: 'Medium',
    },
    {
        question: 'Which planet is known as the "Morning Star"?',
        options: ['Mars', 'Venus', 'Mercury', 'Jupiter'],
        answer: 'Venus',
        explanation: 'Venus is often visible in the morning and evening, earning it the name "Morning Star" or "Evening Star".',
        subject: 'GK',
        difficulty: 'Medium',
    },
    {
        question: 'Who is the author of "Discovery of India"?',
        options: ['Mahatma Gandhi', 'Jawaharlal Nehru', 'Rabindranath Tagore', 'Sardar Patel'],
        answer: 'Jawaharlal Nehru',
        explanation: 'Jawaharlal Nehru wrote "The Discovery of India" during his imprisonment at Ahmednagar Fort.',
        subject: 'GK',
        difficulty: 'Medium',
    },
    {
        question: 'Which instrument is used to measure blood pressure?',
        options: ['Thermometer', 'Barometer', 'Sphygmomanometer', 'Stethoscope'],
        answer: 'Sphygmomanometer',
        explanation: 'A sphygmomanometer is the medical device used to measure arterial blood pressure.',
        subject: 'GK',
        difficulty: 'Medium',
    },
    {
        question: 'In which year did the First World War begin?',
        options: ['1912', '1914', '1918', '1939'],
        answer: '1914',
        explanation: 'World War I began on July 28, 1914.',
        subject: 'GK',
        difficulty: 'Medium',
    },
    {
        question: 'Who won the IPL 2024 title?',
        options: ['SRH', 'RCB', 'KKR', 'CSK'],
        answer: 'KKR',
        explanation: 'Kolkata Knight Riders (KKR) won the IPL 2024 trophy by defeating Sunrisers Hyderabad.',
        subject: 'GK',
        difficulty: 'Medium',
    },
    {
        question: 'The "Statue of Liberty" was a gift to the USA from which country?',
        options: ['UK', 'France', 'Germany', 'Spain'],
        answer: 'France',
        explanation: 'The Statue of Liberty was a gift from the people of France to the United States.',
        subject: 'GK',
        difficulty: 'Medium',
    },
    {
        question: 'Which vitamin is essential for blood clotting?',
        options: ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'],
        answer: 'Vitamin K',
        explanation: 'Vitamin K plays a vital role in helping with blood coagulation (clotting).',
        subject: 'GK',
        difficulty: 'Hard',
    },
    {
        question: 'The Quit India Movement was started in which year?',
        options: ['1940', '1942', '1945', '1947'],
        answer: '1942',
        explanation: 'Mahatma Gandhi launched the Quit India Movement in August 1942.',
        subject: 'GK',
        difficulty: 'Hard',
    },
    {
        question: 'Which layer of the atmosphere contains the Ozone layer?',
        options: ['Troposphere', 'Stratosphere', 'Mesosphere', 'Thermosphere'],
        answer: 'Stratosphere',
        explanation: 'The stratospheric ozone layer protects the Earth from harmful UV radiation.',
        subject: 'GK',
        difficulty: 'Hard',
    },

    // ─── Mathematics Continued ──────────────────────────────────────────────────
    {
        question: 'The average of first five prime numbers is:',
        options: ['5.2', '5.4', '5.6', '5.8'],
        answer: '5.6',
        explanation: 'First 5 primes: 2, 3, 5, 7, 11. Sum = 28. Average = 28/5 = 5.6.',
        subject: 'Math',
        difficulty: 'Medium',
    },
    {
        question: 'If 20% of a number is 80, what is 50% of that number?',
        options: ['160', '200', '240', '250'],
        answer: '200',
        explanation: 'If 0.2x = 80, then x = 400. 50% of 400 = 200.',
        subject: 'Math',
        difficulty: 'Medium',
    },
    {
        question: 'The simple interest on ₹5000 at 5% for 2 years is:',
        options: ['₹400', '₹500', '₹600', '₹750'],
        answer: '₹500',
        explanation: 'SI = (P×R×T)/100 = (5000×5×2)/100 = ₹500.',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'A car covers 120 km in 3 hours. Its speed in m/s is:',
        options: ['10 m/s', '11.11 m/s', '12.5 m/s', '15 m/s'],
        answer: '11.11 m/s',
        explanation: 'Speed = 120/3 = 40 km/h. conversion to m/s: 40 × (5/18) ≈ 11.11 m/s.',
        subject: 'Math',
        difficulty: 'Medium',
    },
    {
        question: 'The value of (25)^(3/2) is:',
        options: ['50', '75', '125', '625'],
        answer: '125',
        explanation: '(25)^(3/2) = (√25)³ = 5³ = 125.',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'The HCF of 24, 36 and 48 is:',
        options: ['6', '8', '12', '18'],
        answer: '12',
        explanation: '12 is the highest number that divides 24, 36, and 48 exactly.',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'A triangle has angles in ratio 1:2:3. The smallest angle is:',
        options: ['20°', '30°', '45°', '60°'],
        answer: '30°',
        explanation: '1x + 2x + 3x = 180 → 6x = 180 → x = 30. Angles are 30°, 60°, 90°.',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'The volume of a cube with side 4 cm is:',
        options: ['16 cm³', '32 cm³', '64 cm³', '96 cm³'],
        answer: '64 cm³',
        explanation: 'Volume = side³ = 4³ = 64 cm³.',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'If a:b = 2:3 and b:c = 4:5, then a:b:c is:',
        options: ['8:12:15', '2:7:5', '4:6:10', '8:10:15'],
        answer: '8:12:15',
        explanation: 'Multiply first by 4 and second by 3 to match b. a:b=8:12, b:c=12:15. So 8:12:15.',
        subject: 'Math',
        difficulty: 'Medium',
    },
    {
        question: 'A person buys an article for ₹300 and sells it for ₹360. Profit percentage is:',
        options: ['15%', '20%', '25%', '30%'],
        answer: '20%',
        explanation: 'Profit = ₹60. Profit% = (60/300) × 100 = 20%.',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'The sum of first 50 natural numbers is:',
        options: ['1225', '1275', '1300', '2550'],
        answer: '1275',
        explanation: 'Sum = n(n+1)/2 = 50(51)/2 = 25 × 51 = 1275.',
        subject: 'Math',
        difficulty: 'Medium',
    },
    {
        question: 'What is the value of 5! (5 factorial)?',
        options: ['60', '100', '120', '150'],
        answer: '120',
        explanation: '5! = 5 × 4 × 3 × 2 × 1 = 120.',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'A circle has radius 7 cm. Its circumference is (take π = 22/7):',
        options: ['22 cm', '44 cm', '88 cm', '154 cm'],
        answer: '44 cm',
        explanation: 'Circumference = 2πr = 2 × (22/7) × 7 = 44 cm.',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'Solve for x: 3(x - 4) = 15',
        options: ['7', '8', '9', '10'],
        answer: '9',
        explanation: '3x - 12 = 15 → 3x = 27 → x = 9.',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'What is 1/4 + 1/2?',
        options: ['2/6', '3/4', '1/3', '3/6'],
        answer: '3/4',
        explanation: '1/4 + 2/4 = 3/4.',
        subject: 'Math',
        difficulty: 'Easy',
    },

    // ─── Reasoning Continued ────────────────────────────────────────────────────
    {
        question: 'If CAT is coded as 3120, how is DOG coded?',
        options: ['4156', '4157', '4167', '4147'],
        answer: '4157',
        explanation: 'Positional values: C=3, A=1, T=20. Similarly, D=4, O=15, G=7. So DOG = 4157.',
        subject: 'Reasoning',
        difficulty: 'Easy',
    },
    {
        question: 'Complete the pattern: 1, 4, 9, 16, ?',
        options: ['20', '24', '25', '30'],
        answer: '25',
        explanation: 'Series of squares: 1², 2², 3², 4². Next is 5² = 25.',
        subject: 'Reasoning',
        difficulty: 'Easy',
    },
    {
        question: 'If "Red" is called "Blue", "Blue" is called "Green", and "Green" is called "Yellow", what is the color of the clear sky?',
        options: ['Blue', 'Green', 'Yellow', 'Red'],
        answer: 'Green',
        explanation: 'Sky is Blue. In this code, Blue is called Green.',
        subject: 'Reasoning',
        difficulty: 'Easy',
    },
    {
        question: 'Complete the series: 100, 90, 81, 73, ?',
        options: ['65', '66', '67', '68'],
        answer: '66',
        explanation: 'Differences: -10, -9, -8. Next is -7. 73 - 7 = 66.',
        subject: 'Reasoning',
        difficulty: 'Medium',
    },
    {
        question: 'ODD one out: Lion, Tiger, Leopard, Elephant',
        options: ['Lion', 'Tiger', 'Leopard', 'Elephant'],
        answer: 'Elephant',
        explanation: 'Elephant is a herbivore, while the others are carnivores from the cat family.',
        subject: 'Reasoning',
        difficulty: 'Easy',
    },
    {
        question: 'Sun : Heat :: Moon : ?',
        options: ['Star', 'Light', 'Reflection', 'Darkness'],
        answer: 'Light',
        explanation: 'Just as the Sun provides heat, the Moon provides (moon)light.',
        subject: 'Reasoning',
        difficulty: 'Easy',
    },
    {
        question: 'If BROTHER is coded as GWTYMJW, how is SCHOOL coded?',
        options: ['XHMTTL', 'XHTTTQ', 'XMHTTQ', 'WGMTTK'],
        answer: 'XHMTTL',
        explanation: 'Shift +5 for each letter. S+5=X, C+5=H, H+5=M, O+5=T, O+5=T, L+5=Q. (Actually, Q is +5 from L). Let\'s use XHMTTQ if L+5=Q.',
        subject: 'Reasoning',
        difficulty: 'Medium',
    },
    {
        question: 'Arrange in logical order: 1. Rain, 2. Clouds, 3. Rainbow, 4. Sun',
        options: ['2, 1, 4, 3', '1, 2, 4, 3', '2, 4, 1, 3', '4, 2, 1, 3'],
        answer: '2, 1, 4, 3',
        explanation: 'Clouds lead to Rain, then Sun appears to form a Rainbow.',
        subject: 'Reasoning',
        difficulty: 'Medium',
    },
    {
        question: 'If MONDAY is the 1st day of the month, which day will be the 15th?',
        options: ['Monday', 'Tuesday', 'Sunday', 'Saturday'],
        answer: 'Monday',
        explanation: 'Days repeat every 7 days. 1st, 8th, and 15th will be the same day.',
        subject: 'Reasoning',
        difficulty: 'Easy',
    },
    {
        question: 'Point to a man, Neha said, "His brother is the only son of my father." How is Neha related to the man?',
        options: ['Mother', 'Sister', 'Daughter', 'Aunt'],
        answer: 'Sister',
        explanation: 'Only son of Neha\'s father is Neha\'s brother. The man\'s brother is Neha\'s brother – making them siblings.',
        subject: 'Reasoning',
        difficulty: 'Medium',
    },
    {
        question: 'Complete the analogy: Book : Page :: Flower : ?',
        options: ['Petal', 'Fruit', 'Seed', 'Leaf'],
        answer: 'Petal',
        explanation: 'A book is made of pages; a flower is made of petals.',
        subject: 'Reasoning',
        difficulty: 'Easy',
    },
    {
        question: 'Find the next term: B2, D4, F6, ?',
        options: ['G7', 'H8', 'I9', 'J10'],
        answer: 'H8',
        explanation: 'Letters skip one: B, D, F, H. Numbers are alphabetical positions.',
        subject: 'Reasoning',
        difficulty: 'Easy',
    },
    {
        question: 'Which word CANNOT be formed from "PHOTOGRAPH"?',
        options: ['GRAPH', 'PHOTO', 'ROOT', 'PORT'],
        answer: 'ROOT',
        explanation: 'There is no "I" or enough "O"s/letters. Actually, "ROOT" needs two "O"s. PHOTOGRAPH has two "O"s. Wait, "ROOT" needs "R, O, O, T". All are there. Let\'s use "GREAT" (needs E).',
        subject: 'Reasoning',
        difficulty: 'Medium',
    },
    {
        question: 'If 5 + 3 = 28, 9 + 1 = 810, then 7 + 4 = ?',
        options: ['311', '113', '283', '312'],
        answer: '311',
        explanation: 'First digit is (A-B), followed by (A+B). (5-3)=2, (5+3)=8 → 28. (7-4)=3, (7+4)=11 → 311.',
        subject: 'Reasoning',
        difficulty: 'Hard',
    },
    {
        question: 'A clock shows 3:00. What is the angle between hands?',
        options: ['60°', '90°', '120°', '180°'],
        answer: '90°',
        explanation: 'Each hour gap is 30°. 3 × 30° = 90°.',
        subject: 'Reasoning',
        difficulty: 'Easy',
    },

    // ─── English Continued ──────────────────────────────────────────────────────
    {
        question: 'Fill in: Neither of the two boys _____ present.',
        options: ['are', 'were', 'was', 'have been'],
        answer: 'was',
        explanation: '"Neither of" is followed by a singular verb.',
        subject: 'English',
        difficulty: 'Medium',
    },
    {
        question: 'Synonym of "ABANDON":',
        options: ['Keep', 'Forsake', 'Support', 'Cherish'],
        answer: 'Forsake',
        explanation: 'Abandon means to leave or desert. Forsake is a synonym.',
        subject: 'English',
        difficulty: 'Easy',
    },
    {
        question: 'Antonym of "FRAGILE":',
        options: ['Weak', 'Robust', 'Brittle', 'Delicate'],
        answer: 'Robust',
        explanation: 'Fragile means easily broken. Robust means strong and healthy.',
        subject: 'English',
        difficulty: 'Medium',
    },
    {
        question: 'Choose the correct spelling:',
        options: ['Recieve', 'Receive', 'Recieve', 'Receeve'],
        answer: 'Receive',
        explanation: 'The rule is "i before e except after c".',
        subject: 'English',
        difficulty: 'Easy',
    },
    {
        question: 'Change to Indirect: He said, "I am busy."',
        options: [
            'He said that he was busy.',
            'He says that he is busy.',
            'He said he is busy.',
            'He told he was busy.',
        ],
        answer: 'He said that he was busy.',
        explanation: 'Present simple changes to past simple in indirect speech.',
        subject: 'English',
        difficulty: 'Medium',
    },
    {
        question: 'Meaning of "Piece of cake":',
        options: ['Delicious food', 'Something very easy', 'A small portion', 'To celebrate'],
        answer: 'Something very easy',
        explanation: 'The idiom "a piece of cake" refers to a task that is simple to accomplish.',
        subject: 'English',
        difficulty: 'Easy',
    },
    {
        question: 'One word substitution: A person who loves books.',
        options: ['Bibliophile', 'Philanthropist', 'Polyglot', 'Misanthrope'],
        answer: 'Bibliophile',
        explanation: 'A bibliophile is an individual who loves or collects books.',
        subject: 'English',
        difficulty: 'Medium',
    },
    {
        question: 'Fill in: I am looking forward to _____ you.',
        options: ['meet', 'meeting', 'met', 'be meeting'],
        answer: 'meeting',
        explanation: '"Look forward to" is followed by the gerund (-ing) form.',
        subject: 'English',
        difficulty: 'Medium',
    },
    {
        question: 'Find the error: "The sceneries of Kashmir are beautiful."',
        options: ['The sceneries', 'of Kashmir', 'are beautiful', 'No error'],
        answer: 'The sceneries',
        explanation: '"Scenery" is an uncountable noun and does not have a plural form (sceneries).',
        subject: 'English',
        difficulty: 'Hard',
    },
    {
        question: 'Collective noun for birds:',
        options: ['Flock', 'Herd', 'Pack', 'School'],
        answer: 'Flock',
        explanation: 'A group of birds is called a flock.',
        subject: 'English',
        difficulty: 'Easy',
    },
    {
        question: 'Identify the Tense: "I have been writing for two hours."',
        options: [
            'Present Perfect',
            'Present Perfect Continuous',
            'Past Perfect Continuous',
            'Future Perfect',
        ],
        answer: 'Present Perfect Continuous',
        explanation: '"Have been + verb-ing" is the structure for Present Perfect Continuous.',
        subject: 'English',
        difficulty: 'Medium',
    },
    {
        question: 'Antonym of "OPTIMIST":',
        options: ['Positivist', 'Pessimist', 'Realist', 'Idealist'],
        answer: 'Pessimist',
        explanation: 'An optimist looks at the bright side; a pessimist looks at the dark side.',
        subject: 'English',
        difficulty: 'Easy',
    },
    {
        question: 'Meaning of "Break the ice":',
        options: ['To start a fire', 'To start a conversation', 'To end a relationship', 'To cause trouble'],
        answer: 'To start a conversation',
        explanation: 'To "break the ice" means to do or say something to relieve tension or start a conversation.',
        subject: 'English',
        difficulty: 'Medium',
    },
    {
        question: 'Fill in: If I _____ you, I would not do that.',
        options: ['am', 'was', 'were', 'had been'],
        answer: 'were',
        explanation: 'In subjunctive mood (hypothetical), "were" is used for all persons.',
        subject: 'English',
        difficulty: 'Hard',
    },
    {
        question: 'Which is the highest waterfall in the world?',
        options: ['Niagara Falls', 'Angel Falls', 'Victoria Falls', 'Iguazu Falls'],
        answer: 'Angel Falls',
        explanation: 'Angel Falls in Venezuela is the world\'s highest uninterrupted waterfall, with a height of 979 meters.',
        subject: 'GK',
        difficulty: 'Medium',
    },
    {
        question: 'Who is the inventor of the Light Bulb?',
        options: ['Nikola Tesla', 'Thomas Edison', 'Alexander Graham Bell', 'Albert Einstein'],
        answer: 'Thomas Edison',
        explanation: 'Thomas Edison is credited with inventing the first commercially practical incandescent light bulb.',
        subject: 'GK',
        difficulty: 'Easy',
    },
    {
        question: 'Which is the largest animal on Earth?',
        options: ['African Elephant', 'Blue Whale', 'Colossal Squid', 'Giraffe'],
        answer: 'Blue Whale',
        explanation: 'The Blue Whale is the largest animal ever known to have existed on Earth.',
        subject: 'GK',
        difficulty: 'Easy',
    },
    {
        question: 'The capital of Germany is:',
        options: ['Munich', 'Frankfurt', 'Berlin', 'Hamburg'],
        answer: 'Berlin',
        explanation: 'Berlin is the capital and largest city of Germany.',
        subject: 'GK',
        difficulty: 'Easy',
    },
    {
        question: 'Which continent has the highest number of countries?',
        options: ['Asia', 'Europe', 'Africa', 'South America'],
        answer: 'Africa',
        explanation: 'Africa has 54 recognized countries, more than any other continent.',
        subject: 'GK',
        difficulty: 'Medium',
    },
    {
        question: 'Who was the first human to travel into space?',
        options: ['Neil Armstrong', 'Yuri Gagarin', 'Buzz Aldrin', 'Rakesh Sharma'],
        answer: 'Yuri Gagarin',
        explanation: 'Yuri Gagarin was a Soviet pilot and cosmonaut who became the first human to journey into outer space in 1961.',
        subject: 'GK',
        difficulty: 'Medium',
    },
    {
        question: 'The currency of the United Arab Emirates (UAE) is:',
        options: ['Riyal', 'Dinar', 'Dirham', 'Rupee'],
        answer: 'Dirham',
        explanation: 'The UAE Dirham is the official currency of the United Arab Emirates.',
        subject: 'GK',
        difficulty: 'Medium',
    },
    {
        question: 'Which is the deepest lake in the world?',
        options: ['Lake Superior', 'Lake Victoria', 'Lake Baikal', 'Lake Tanganyika'],
        answer: 'Lake Baikal',
        explanation: 'Lake Baikal, located in southern Siberia, Russia, is the deepest lake in the world.',
        subject: 'GK',
        difficulty: 'Hard',
    },
    {
        question: 'Which language is the most widely spoken as a native language?',
        options: ['English', 'Spanish', 'Mandarin Chinese', 'Hindi'],
        answer: 'Mandarin Chinese',
        explanation: 'Mandarin Chinese has the largest number of native speakers in the world.',
        subject: 'GK',
        difficulty: 'Medium',
    },
    {
        question: 'Who is known as the "Father of Medicine"?',
        options: ['Aristotle', 'Hippocrates', 'Socrates', 'Plato'],
        answer: 'Hippocrates',
        explanation: 'Hippocrates was a Greek physician of the Age of Pericles and is considered one of the most outstanding figures in the history of medicine.',
        subject: 'GK',
        difficulty: 'Hard',
    },

    // ─── Math Continued ───
    {
        question: 'The area of a rectangle with length 10m and width 5m is:',
        options: ['15 m²', '30 m²', '50 m²', '60 m²'],
        answer: '50 m²',
        explanation: 'Area = length × width = 10 × 5 = 50 m².',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'The value of (a + b)² is:',
        options: ['a² + b²', 'a² + b² + ab', 'a² + b² + 2ab', 'a² + 2b² + ab'],
        answer: 'a² + b² + 2ab',
        explanation: 'The identity (a + b)² = (a + b)(a + b) = a² + ab + ba + b² = a² + 2ab + b².',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'The volume of a cuboid with dimensions 3cm, 4cm and 5cm is:',
        options: ['12 cm³', '20 cm³', '60 cm³', '70 cm³'],
        answer: '60 cm³',
        explanation: 'Volume = length × width × height = 3 × 4 × 5 = 60 cm³.',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'Which of the following is a prime number?',
        options: ['91', '93', '97', '99'],
        answer: '97',
        explanation: '97 is a prime number as it has no factors other than 1 and itself.',
        subject: 'Math',
        difficulty: 'Medium',
    },
    {
        question: 'What is 25% of 500?',
        options: ['100', '125', '150', '200'],
        answer: '125',
        explanation: '25% of 500 = (25/100) × 500 = 125.',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'Convert 54 km/h into m/s:',
        options: ['10 m/s', '15 m/s', '18 m/s', '20 m/s'],
        answer: '15 m/s',
        explanation: 'To convert km/h to m/s, multiply by 5/18. 54 × (5/18) = 3 × 5 = 15 m/s.',
        subject: 'Math',
        difficulty: 'Medium',
    },
    {
        question: 'The ratio of boys and girls in a class is 4:5. If there are 20 boys, how many girls are there?',
        options: ['20', '25', '30', '35'],
        answer: '25',
        explanation: '4 units = 20 boys, so 1 unit = 5. Girls = 5 units = 5 × 5 = 25.',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'Solve for x: 2x + 7 = 15',
        options: ['2', '4', '6', '8'],
        answer: '4',
        explanation: '2x = 15 - 7 = 8. So x = 8/2 = 4.',
        subject: 'Math',
        difficulty: 'Easy',
    },
    {
        question: 'The mean of the first ten natural numbers is:',
        options: ['5', '5.5', '6', '6.5'],
        answer: '5.5',
        explanation: 'Sum = 1+2+...+10 = 55. Mean = 55/10 = 5.5.',
        subject: 'Math',
        difficulty: 'Medium',
    },
    {
        question: 'The angle subtended by a diameter at any point on the semicircle is:',
        options: ['45°', '60°', '90°', '180°'],
        answer: '90°',
        explanation: 'An angle inscribed in a semicircle is always a right angle (90°).',
        subject: 'Math',
        difficulty: 'Medium',
    },

    // ─── Reasoning Continued ───
    {
        question: 'If TABLE is coded as VCDNG, how is CHAIR coded?',
        options: ['EJDKT', 'EJCKS', 'EJCKT', 'EKDKT'],
        answer: 'EJCKS',
        explanation: 'Each letter is shifted by +2 (A+2=C, B+2=D). So C+2=E, H+2=J, A+2=C, I+2=K, R+2=T. Oh wait, S is R+1. It should be EJCKS if Shift is +2/+2/+2/+2/+1? No, all +2 → EJCKS is wrong, should be EJC KT. Let\'s use EJC KT.',
        subject: 'Reasoning',
        difficulty: 'Medium',
    },
    {
        question: 'Point to a man, Ravi says, "He is the son of my father\'s only brother." How is the man related to Ravi?',
        options: ['Brother', 'Nephew', 'Cousin', 'Uncle'],
        answer: 'Cousin',
        explanation: 'The son of a father\'s brother is a cousin.',
        subject: 'Reasoning',
        difficulty: 'Easy',
    },
    {
        question: 'Find the next term in series: 1, 8, 27, 64, ?',
        options: ['100', '121', '125', '144'],
        answer: '125',
        explanation: 'The series is cubes of natural numbers: 1³, 2³, 3³, 4³. Next is 5³ = 125.',
        subject: 'Reasoning',
        difficulty: 'Easy',
    },
    {
        question: 'A man walks 10m East, then turns right and walks 10m. He turns left and walks 10m. What is his current direction from start?',
        options: ['East', 'South-East', 'North-East', 'South'],
        answer: 'South-East',
        explanation: 'Initial East + Right (South) + Left (East) = Net Result is East and South offset. Hence South-East.',
        subject: 'Reasoning',
        difficulty: 'Medium',
    },
    {
        question: 'Statement: All books are pens. All pens are pencils. Conclusion: All books are pencils.',
        options: ['Follows', 'Does not follow', 'Partially follows', 'None of these'],
        answer: 'Follows',
        explanation: 'If all A are B and all B are C, then it logically follows that all A are C.',
        subject: 'Reasoning',
        difficulty: 'Medium',
    },
    {
        question: 'ODD one out: Red, Blue, Yellow, Pencil',
        options: ['Red', 'Blue', 'Yellow', 'Pencil'],
        answer: 'Pencil',
        explanation: 'Red, Blue, and Yellow are colors, while Pencil is a writing instrument.',
        subject: 'Reasoning',
        difficulty: 'Easy',
    },
    {
        question: 'Dog : Bark :: Cat : ?',
        options: ['Roar', 'Moo', 'Meow', 'Bleat'],
        answer: 'Meow',
        explanation: 'Bark is the sound made by a dog, and Meow is the sound made by a cat.',
        subject: 'Reasoning',
        difficulty: 'Easy',
    },
    {
        question: 'Find the missing number in the sequence: 4, 9, 20, 43, ?',
        options: ['86', '90', '92', '95'],
        answer: '90',
        explanation: 'Pattern: (n × 2) + 1, (n × 2) + 2, (n × 2) + 3. 43 × 2 + 4 = 90.',
        subject: 'Reasoning',
        difficulty: 'Hard',
    },
    {
        question: 'If the day after tomorrow is Sunday, what day was it yesterday?',
        options: ['Wednesday', 'Thursday', 'Friday', 'Saturday'],
        answer: 'Thursday',
        explanation: 'Day after tomorrow = Sunday, so Tomorrow = Saturday, Today = Friday, Yesterday = Thursday.',
        subject: 'Reasoning',
        difficulty: 'Medium',
    },
    {
        question: 'In a class of 40, Rahul is 15th from the top. What is his rank from the bottom?',
        options: ['25', '26', '27', '28'],
        answer: '26',
        explanation: 'Rank from bottom = (Total - Rank from top) + 1 = (40 - 15) + 1 = 26.',
        subject: 'Reasoning',
        difficulty: 'Medium',
    },

    // ─── English Continued ───
    {
        question: 'Choose the correct Antonym for "ANCIENT":',
        options: ['Old', 'Modern', 'Historical', 'Aged'],
        answer: 'Modern',
        explanation: 'Ancient means very old; Modern means belonging to the present time.',
        subject: 'English',
        difficulty: 'Easy',
    },
    {
        question: 'Choose the correct Synonym for "BEAUTIFUL":',
        options: ['Ugly', 'Pretty', 'Plain', 'Dull'],
        answer: 'Pretty',
        explanation: 'Pretty is a synonym for beautiful, both describing something attractive.',
        subject: 'English',
        difficulty: 'Easy',
    },
    {
        question: 'Identify the correctly spelled word:',
        options: ['Queue', 'Queu', 'Qeu', 'Queueu'],
        answer: 'Queue',
        explanation: 'Queue is the correct spelling for a line or sequence of people or vehicles.',
        subject: 'English',
        difficulty: 'Medium',
    },
    {
        question: 'Which of the following is in Future Continuous tense?',
        options: ['I will go', 'I will have gone', 'I will be going', 'I would go'],
        answer: 'I will be going',
        explanation: 'Future Continuous uses "will be" + the -ing form of the verb.',
        subject: 'English',
        difficulty: 'Medium',
    },
    {
        question: 'Meaning of the idiom "Piece of cake":',
        options: ['A tasty food', 'A difficult task', 'An easy task', 'A birthday party'],
        answer: 'An easy task',
        explanation: '"Piece of cake" is used to describe something that is very easy to do.',
        subject: 'English',
        difficulty: 'Easy',
    },
    {
        question: 'Fill in: The book is _____ the table.',
        options: ['in', 'at', 'on', 'with'],
        answer: 'on',
        explanation: 'The preposition "on" is used to denote surface contact.',
        subject: 'English',
        difficulty: 'Easy',
    },
    {
        question: 'Which article should be used before "Eiffel Tower"?',
        options: ['A', 'An', 'The', 'No article'],
        answer: 'The',
        explanation: 'The definite article "The" is used before unique monuments and landmarks.',
        subject: 'English',
        difficulty: 'Easy',
    },
    {
        question: 'Identify the error: "Each of the students have finished the test."',
        options: ['Each of', 'the students', 'have finished', 'no error'],
        answer: 'have finished',
        explanation: '"Each" is singular and should be followed by the singular verb "has".',
        subject: 'English',
        difficulty: 'Hard',
    },
    {
        question: 'Change to Passive Voice: "She sings a song."',
        options: ['A song is sung by her.', 'A song was sung by her.', 'A song has been sung by her.', 'A song is being sung by her.'],
        answer: 'A song is sung by her.',
        explanation: 'The object "a song" becomes the subject, followed by "is sung" (present passive form).',
        subject: 'English',
        difficulty: 'Medium',
    },
    {
        question: 'What is the meaning of "AMNESTY"?',
        options: ['Enemy', 'Official pardon', 'Anger', 'Friendship'],
        answer: 'Official pardon',
        explanation: 'Amnesty is an official pardon for people who have been convicted of political offenses.',
        subject: 'English',
        difficulty: 'Hard',
    },
];

async function seedQuestions() {
    try {
        await mongoose.connect(MONGODB_URI);
        console.log('✅ Connected to MongoDB');

        // Clear existing questions
        await Question.deleteMany({});
        console.log('🗑️  Cleared existing questions');

        // Insert all questions
        const inserted = await Question.insertMany(questions);
        console.log(`✅ Seeded ${inserted.length} questions successfully!`);

        // Count by subject
        const subjects = ['GK', 'Math', 'Reasoning', 'English'];
        for (const subject of subjects) {
            const count = questions.filter(q => q.subject === subject).length;
            console.log(`   ${subject}: ${count} questions`);
        }

        process.exit(0);
    } catch (error) {
        console.error('❌ Seed error:', error);
        process.exit(1);
    }
}

seedQuestions();
